using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Xml;

namespace EasyHomeServer.Modules.Avahi.Avahi;

/// <summary>One mDNS service to advertise on the LAN.</summary>
public sealed record ServiceDefinition
{
    /// <summary>
    /// Stable key identifying what this advertisement is for, used as the filename. For a
    /// container advertisement this is the container name.
    /// </summary>
    public required string Key { get; init; }

    /// <summary>Service name as it appears to browsers, for example "Nginx on debian".</summary>
    public required string DisplayName { get; init; }

    /// <summary>DNS-SD service type, for example <c>_http._tcp</c>.</summary>
    public required string ServiceType { get; init; }

    /// <summary>Port the service answers on.</summary>
    public required int Port { get; init; }

    /// <summary>
    /// Host that provides the service, when it is not this machine. Used for a container holding
    /// its own address on the LAN: the service lives at its address, not the host's.
    /// </summary>
    /// <remarks>
    /// Must be fully qualified — avahi does not append <c>.local</c> — and must resolve, which is
    /// why an entry in <see cref="AvahiHostsFile"/> has to accompany it. Null means this machine,
    /// which avahi resolves itself.
    /// </remarks>
    public string? HostName { get; init; }

    /// <summary>The address behind <see cref="HostName"/>, needed for its static host record.</summary>
    public string? HostAddress { get; init; }

    /// <summary>TXT records, published as key=value pairs.</summary>
    public ImmutableDictionary<string, string> TxtRecords { get; init; } =
        ImmutableDictionary<string, string>.Empty;

    /// <summary>Where this advertisement came from, for display.</summary>
    public required ServiceOrigin Origin { get; init; }

    /// <summary>Container name this came from, when <see cref="Origin"/> is a container.</summary>
    public string? ContainerName { get; init; }

    /// <summary>
    /// Renders the avahi service file.
    /// </summary>
    /// <remarks>
    /// Built with <see cref="XmlWriter"/> rather than string interpolation. Every value here
    /// comes from a container label or name — attacker-influenced in the sense that whoever runs
    /// `docker run` chooses them — and a name containing <c>&lt;</c> would otherwise produce a
    /// malformed file that avahi rejects, silently taking down every advertisement in it.
    /// </remarks>
    public string ToServiceFile()
    {
        var settings = new XmlWriterSettings
        {
            Indent = true,
            IndentChars = "  ",
            Encoding = new UTF8Encoding(false),
            OmitXmlDeclaration = false,
        };

        var buffer = new StringWriterWithEncoding(Encoding.UTF8);

        using (var writer = XmlWriter.Create(buffer, settings))
        {
            writer.WriteStartDocument(standalone: false);
            writer.WriteDocType("service-group", null, "avahi-service.dtd", null);

            writer.WriteComment(
                " Generated by EasyHomeServer. Edits are overwritten; this file is rewritten "
                + "whenever the advertisement changes. ");

            writer.WriteStartElement("service-group");

            // replace-wildcards lets avahi substitute %h with the hostname at publish time, so
            // the advertised name follows a hostname change without rewriting the file.
            writer.WriteStartElement("name");
            writer.WriteAttributeString("replace-wildcards", "yes");
            writer.WriteString(DisplayName);
            writer.WriteEndElement();

            writer.WriteStartElement("service");
            writer.WriteElementString("type", ServiceType);

            // Must precede <port>: the DTD fixes the order, and avahi rejects the file otherwise
            // — silently dropping every service in it.
            if (HostName is { Length: > 0 })
            {
                writer.WriteElementString("host-name", HostName);
            }

            writer.WriteElementString("port", Port.ToString(CultureInfo.InvariantCulture));

            foreach (var (key, value) in TxtRecords.OrderBy(r => r.Key, StringComparer.Ordinal))
            {
                writer.WriteElementString("txt-record", $"{key}={value}");
            }

            writer.WriteEndElement();
            writer.WriteEndElement();
            writer.WriteEndDocument();
        }

        return buffer.ToString();
    }

    /// <summary>
    /// StringWriter reports UTF-16 as its encoding, which XmlWriter would then declare in the
    /// prolog. avahi reads these as UTF-8.
    /// </summary>
    private sealed class StringWriterWithEncoding(Encoding encoding) : StringWriter
    {
        public override Encoding Encoding { get; } = encoding;
    }
}

/// <summary>Where an advertisement came from.</summary>
public enum ServiceOrigin
{
    /// <summary>Derived from a Docker container's labels.</summary>
    Container,

    /// <summary>The management tool advertising itself.</summary>
    Host,
}
